### ISSUE TITLE
How to prepare the hiera yaml file for `auth_config` in `templates/realm.properties.erb`

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#78]
I need prepare hiera yaml file for template [realm.properties.erb](https://github.com/puppet-community/puppet-rundeck/blob/master/templates/realm.properties.erb)

```
rundeck::params::auth_config:
    file:
       admin_user: admin
       admin_password: password
       auth_users: ['user1', 'user2']
      ???
      ???
```
Seems it doesn't work. For example, I need set `/etc/rundeck/realm.properties` to 
```
admin:password,user,admin,architect,deploy,build
user1:abc,user,deploy
user2:xyz,admin
```
So could you please share me the sample of hiera yaml file for this setting?

**Comment by SydOps** [comment]
This works for me, thanks @liamjbennett 

```
rundeck::auth_config:
  file:
    auth_users:
      - username: 'puppet'
        password: 'puppet'
        roles:
          - user
          - admin
          - architect
          - deploy
          - build
```
